# Generated by Django 2.2 on 2020-11-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0002_auto_20201108_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='designation',
            field=models.CharField(choices=[('DGP', 'Director General of Police'), ('ADGP', 'Addl. Director General of Police'), ('IGP', 'Inspector General of Police'), ('DIGP', 'Deputy Inspector General of Police'), ('SPDCP', 'Superintendent of police Deputy Commissioner of Police(Selection Grade)'), ('SPDCPJ', 'Superintendent of police Deputy Commissioner of Police(Junior Management Grade)'), ('ASPADCP', 'Addl. Superintendent of police Addl.Deputy Commissioner of Police'), ('ASP', 'Assistant Superintendent of Police'), ('INSP', 'Inspector of Police'), ('SUB_INSP', 'Sub Inspector of Police.'), ('HVLDRM', 'Asst. Sub. Inspector/Havildar Major'), ('HVLDR', 'Havildar.'), ('LN', 'Lance Naik.'), ('CONS', 'Constable.')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='police_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='police',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='police.Ward'),
        ),
       migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.CharField(choices=[('RJ14W01', 'Mansarovar'), ('RJ14W02', 'Jagatpura'), ('RJ14W03', 'Sanganer'), ('RJ14W04', 'Kachi Basti'), ('RJ14W05', 'Malviya Nagar'), ('RJ14W06', 'Bani Park'), ('RJ14W07', 'Sitapura'), ('RJ14W08', 'Raja Park'), ('RJ14W09', 'Triveni Nagar'), ('RJ14W10', 'Badi Chopat'), ('RJ14W11', 'Chandpole')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
