# Generated by Django 2.2 on 2020-11-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0003_auto_20201108_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='id',
            field=models.CharField(choices=[('HYD01w1', 'Kapra'), ('HYD01w2', 'Uppal'), ('HYD01w3', 'Hayathnagar'), ('HYD01w4', 'L.B Nagar'), ('HYD01w5', 'Saroornagar'), ('HYD02w6', 'Malakpet'), ('HYD02w7', 'Santhosh Nagar'), ('HYD02w8', 'Chandrayangutta'), ('HYD02w9', 'Charminar'), ('HYD02w10', 'Falaknuma'), ('HYD02w11', 'Rajendra nagar'), ('HYD03w12', 'Mehdipatnam'), ('HYD03w13', 'Karwan'), ('HYD03w14', 'Goshamahal'), ('HYD03w15', 'Khairathabad'), ('HYD03w16', 'Jubilee Hills'), ('HYD04w17', 'Amberpet'), ('HYD04w18', 'Musheerabad'), ('HYD04w19', 'Malkajgiri'), ('HYD04w20', 'Secunderabad'), ('HYD04w21', 'Begumpet'), ('HYD05w22', 'Yusufguda'), ('HYD05w23', 'Serilingampelli'), ('HYD05w24', 'Chandannagar'), ('HYD05w25', 'Patancheru')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
