# Generated by Django 2.2 on 2020-11-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police', '0004_auto_20201123_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('Area', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('birth_mark_desc', models.TextField()),
                ('height', models.CharField(max_length=255)),
                ('complexion', models.CharField(max_length=255)),
                ('eyes', models.CharField(max_length=255)),
                ('img', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
    ]
