# Generated by Django 2.2 on 2020-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201108_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoustip',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
