# Generated by Django 2.2 on 2020-11-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Citizen',
            },
        ),
        migrations.AlterModelOptions(
            name='citizen',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
