# Generated by Django 2.2 on 2020-11-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_auto_20201109_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='bhamashah',
        ),
    ]
