# Generated by Django 2.2 on 2020-11-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20201108_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cybercasecategories',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='witness',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
