# Generated by Django 2.2 on 2020-11-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20201108_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='witness',
            name='bahmashah_id',
        ),
    ]
